### ISSUE TITLE
微调报错

### ISSUE THREAD

**Issue by chenzhu005774** [BAAI-DCAI/Bunny#102]
我在合并 LoRA 权重和基础 LLM后，使用sh script/train/finetune_lora.sh 微调模型报错。错误日志如下。请问这是什么问题，如何修改。

Traceback (most recent call last):
  File "/home/Bunny-main/bunny/train/train.py", line 393, in <module>
    train()
  File "/home/Bunny-main/bunny/train/train.py", line 380, in train
    non_lora_state_dict = get_peft_state_non_lora_maybe_zero_3(
  File "/home/Bunny-main/bunny/train/train.py", line 118, in get_peft_state_non_lora_maybe_zero_3
    to_return = {k: maybe_zero_3(v, ignore_status=True).cpu() for k, v in to_return.items()}
  File "/home/Bunny-main/bunny/train/train.py", line 118, in <dictcomp>
    to_return = {k: maybe_zero_3(v, ignore_status=True).cpu() for k, v in to_return.items()}
  File "/home/Bunny-main/bunny/train/train.py", line 81, in maybe_zero_3
    with zero.GatheredParameters([param]):
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 2178, in __exit__
    self.params[0].partition(param_list=self.params, has_been_updated=False)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1329, in partition
    self._partition(param_list, has_been_updated=has_been_updated)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1478, in _partition
    self._partition_param(param, has_been_updated=has_been_updated)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1511, in _partition_param
    free_param(param)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 281, in free_param
    assert not param.ds_active_sub_modules, param.ds_summary()
AssertionError: {'id': 451, 'status': 'AVAILABLE', 'numel': 2949120, 'ds_numel': 2949120, 'shape': (2560, 1152), 'ds_shape': (2560, 1152), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': {2494}, 'ds_tensor.shape': torch.Size([1474560])}
Traceback (most recent call last):
  File "/home/Bunny-main/bunny/train/train.py", line 393, in <module>
    train()
  File "/home/Bunny-main/bunny/train/train.py", line 380, in train
    non_lora_state_dict = get_peft_state_non_lora_maybe_zero_3(
  File "/home/Bunny-main/bunny/train/train.py", line 118, in get_peft_state_non_lora_maybe_zero_3
    to_return = {k: maybe_zero_3(v, ignore_status=True).cpu() for k, v in to_return.items()}
  File "/home/Bunny-main/bunny/train/train.py", line 118, in <dictcomp>
    to_return = {k: maybe_zero_3(v, ignore_status=True).cpu() for k, v in to_return.items()}
  File "/home/Bunny-main/bunny/train/train.py", line 81, in maybe_zero_3
    with zero.GatheredParameters([param]):
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 2178, in __exit__
    self.params[0].partition(param_list=self.params, has_been_updated=False)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1329, in partition
    self._partition(param_list, has_been_updated=has_been_updated)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1478, in _partition
    self._partition_param(param, has_been_updated=has_been_updated)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1511, in _partition_param
    free_param(param)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 281, in free_param
    assert not param.ds_active_sub_modules, param.ds_summary()
AssertionError: {'id': 451, 'status': 'AVAILABLE', 'numel': 2949120, 'ds_numel': 2949120, 'shape': (2560, 1152), 'ds_shape': (2560, 1152), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': {2494}, 'ds_tensor.shape': torch.Size([1474560])}
[2024-07-04 16:56:43,965] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 799
[2024-07-04 16:56:43,966] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 800
[2024-07-04 16:56:43,966] [ERROR] [launch.py:322:sigkill_handler] ['/root/miniconda3/envs/bunny/bin/python', '-u', 'bunny/train/train.py', '--local_rank=1', '--lora_enable', 'True', '--lora_r', '128', '--lora_alpha', '256', '--mm_projector_lr', '2e-5', '--deepspeed', './script/deepspeed/zero3.json', '--model_name_or_path', './outmodel', '--model_type', 'phi-2', '--version', 'bunny', '--data_path', './finetune/test.json', '--image_folder', './finetune/', '--vision_tower', '../siglip-so400m', '--mm_projector_type', 'mlp2x_gelu', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'False', '--bf16', 'True', '--output_dir', './checkpoints-phi-2/bunny-lora-phi-2', '--num_train_epochs', '1', '--per_device_train_batch_size', '8', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '2', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-4', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'none'] exits with return code = 1

**Comment by chenzhu005774** [comment]
我把参数从  --deepspeed ./script/deepspeed/zero3.json \ 修改为  --deepspeed ./script/deepspeed/zero2.json \后能够得到以下微调后的文件。由于我不是非常专业的开发者。所以想请问一下文件如何替换使用呢？
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/e765027d-235f-4d40-835c-203957375baf)

**Comment by Isaachhh** [comment]
> 我把参数从 --deepspeed ./script/deepspeed/zero3.json \ 修改为 --deepspeed ./script/deepspeed/zero2.json \后能够得到以下微调后的文件。 ![image](https://private-user-images.githubusercontent.com/22974327/345778523-6ff8a492-5945-4cc5-a11c-4cfb244399bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTc3MjMsIm5iZiI6MTcyMDA5NzQyMywicGF0aCI6Ii8yMjk3NDMyNy8zNDU3Nzg1MjMtNmZmOGE0OTItNTk0NS00Y2M1LWExMWMtNGNmYjI0NDM5OWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MjlkYjBlMDYyNDVmMTFhMjk5NDNhMGFhNGE0NGYyMDM5YjMwYzUyNWJhYTM0MTNiN2NlMDRlNzMxMDFmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nx45zNqu8wUcNvuiZs7lTeeeuwNgfiseJ2eEQOh-Gpc)
> 
> 由于我不是非常专业的开发者。我在直接使用 或者 合并的时候都报这个错误： ![image](https://private-user-images.githubusercontent.com/22974327/345777929-33c9d0d4-04bb-411d-aeaf-e0fe2299bf1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTc3MjMsIm5iZiI6MTcyMDA5NzQyMywicGF0aCI6Ii8yMjk3NDMyNy8zNDU3Nzc5MjktMzNjOWQwZDQtMDRiYi00MTFkLWFlYWYtZTBmZTIyOTliZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5M2I2NGJhOTI4MWExMTNkYmJiNTUyZDAzYzQyZTRiNDU5NDQyMjAxZmNkNDEzYjFhMDM5MGExNzM5NGE0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DgSpou3d-OABimBAQ4EIxJx2RPwIHP8UQjvwm_cgzEY) ![image](https://private-user-images.githubusercontent.com/22974327/345778750-2a95b94a-d01e-4c78-9e13-962741b9fb63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTc3MjMsIm5iZiI6MTcyMDA5NzQyMywicGF0aCI6Ii8yMjk3NDMyNy8zNDU3Nzg3NTAtMmE5NWI5NGEtZDAxZS00Yzc4LTllMTMtOTYyNzQxYjlmYjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZGJmZjc4YTliZTcxNzMwOWQyZDA1ZjBiMmM2N2Q4ZDIyZmM1OTEwNDA3NjA1OTg5Mzg5YTMyZmE4Yjk0YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZX0CsFhu7If0rfXAVs_klKNwWt5ds7cWFenakmLNWF0)

--model-base ./outmodel

**Comment by chenzhu005774** [comment]
> > 我把参数从 --deepspeed ./script/deepspeed/zero3.json \ 修改为 --deepspeed ./script/deepspeed/zero2.json \后能够得到以下微调后的文件。 ![image](https://private-user-images.githubusercontent.com/22974327/345778523-6ff8a492-5945-4cc5-a11c-4cfb244399bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTc3MjMsIm5iZiI6MTcyMDA5NzQyMywicGF0aCI6Ii8yMjk3NDMyNy8zNDU3Nzg1MjMtNmZmOGE0OTItNTk0NS00Y2M1LWExMWMtNGNmYjI0NDM5OWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MjlkYjBlMDYyNDVmMTFhMjk5NDNhMGFhNGE0NGYyMDM5YjMwYzUyNWJhYTM0MTNiN2NlMDRlNzMxMDFmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nx45zNqu8wUcNvuiZs7lTeeeuwNgfiseJ2eEQOh-Gpc)
> > 由于我不是非常专业的开发者。我在直接使用 或者 合并的时候都报这个错误： ![image](https://private-user-images.githubusercontent.com/22974327/345777929-33c9d0d4-04bb-411d-aeaf-e0fe2299bf1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTc3MjMsIm5iZiI6MTcyMDA5NzQyMywicGF0aCI6Ii8yMjk3NDMyNy8zNDU3Nzc5MjktMzNjOWQwZDQtMDRiYi00MTFkLWFlYWYtZTBmZTIyOTliZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5M2I2NGJhOTI4MWExMTNkYmJiNTUyZDAzYzQyZTRiNDU5NDQyMjAxZmNkNDEzYjFhMDM5MGExNzM5NGE0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DgSpou3d-OABimBAQ4EIxJx2RPwIHP8UQjvwm_cgzEY) ![image](https://private-user-images.githubusercontent.com/22974327/345778750-2a95b94a-d01e-4c78-9e13-962741b9fb63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTc3MjMsIm5iZiI6MTcyMDA5NzQyMywicGF0aCI6Ii8yMjk3NDMyNy8zNDU3Nzg3NTAtMmE5NWI5NGEtZDAxZS00Yzc4LTllMTMtOTYyNzQxYjlmYjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZGJmZjc4YTliZTcxNzMwOWQyZDA1ZjBiMmM2N2Q4ZDIyZmM1OTEwNDA3NjA1OTg5Mzg5YTMyZmE4Yjk0YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZX0CsFhu7If0rfXAVs_klKNwWt5ds7cWFenakmLNWF0)
> 
> --model-base ./outmodel

感谢 我修改 model-base的参数后能够正常合并也能够使用
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/49da822c-9c48-4e0b-8dca-032c378f9e2c)
运行加载模型。
我的合并文件结构如下：
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/b1441d4c-7aee-4d5a-a915-70d3502deaef)
但是我想通过Transform直接加载模型：
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/0787675d-c1a6-4266-a722-4a79b43e06a7)
显示在我合并的目录中缺少了
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/c8079437-4328-4a45-ae75-dfc5b1f0af73)
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/f25dd373-0254-4744-bafd-f76ac48747d5)
这两个文件我在源码中cp过来了
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/4e53d880-f22a-4524-9d2e-9db5dd861d05)

然后我直接使用Transform加载模型调用：
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/25a407b8-ab9c-47f3-a244-0807beac88aa)
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/cead25dd-707e-4c86-b7b5-b2015f197cc6)

提示没有process_images。这个应当如何修改呢，

**Comment by Isaachhh** [comment]
The snippet in [Quickstart](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#quickstart) is used for Bunny-v1.0-3B (SigLIP + Phi-2) and so on. We manually combine some configuration code into a single file for users' convenience. Also, you can check [modeling_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/modeling_bunny_phi.py) and [configuration_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/configuration_bunny_phi.py) and their related parts in the source code of Bunny to see the difference.

For other models including models trained by yourself, we currently only support loading them with installing source code of Bunny. Or you can copy [modeling_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/modeling_bunny_phi.py) and [configuration_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/configuration_bunny_phi.py) into your model and edit config.json.

BTW, `offset_bos` should be 0 for Phi-2-based Bunny.

**Comment by chenzhu005774** [comment]
> The snippet in [Quickstart](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#quickstart) is used for Bunny-v1.0-3B (SigLIP + Phi-2) and so on. We manually combine some configuration code into a single file for users' convenience. Also, you can check [modeling_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/modeling_bunny_phi.py) and [configuration_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/configuration_bunny_phi.py) and their related parts in the source code of Bunny to see the difference.
> 
> For other models including models trained by yourself, we currently only support loading them with installing source code of Bunny. Or you can copy [modeling_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/modeling_bunny_phi.py) and [configuration_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/configuration_bunny_phi.py) into your model and edit config.json.
> 
> BTW, `offset_bos` should be 0 for Phi-2-based Bunny.

好的 明白 谢谢了。
