### ISSUE TITLE
Trying to test checkpoint of a model during training process

### ISSUE THREAD

**Issue by Wintoplay** [BAAI-DCAI/Bunny#135]
I tried to merge Lora adapter of a model in training process, but I get this result
Loading Bunny from base model...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File ".../Bunny/script/merge_lora_weights.py", line 26, in <module>
    merge_lora(args)
  File ".../Bunny/script/merge_lora_weights.py", line 10, in merge_lora
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, args.model_base, model_name,
  File ".../Bunny/bunny/model/builder.py", line 67, in load_pretrained_model
    model = BunnyLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True,
  File ".../.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4225, in from_pretrained
    ) = cls._load_pretrained_model(
  File ".../.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4728, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File ".../.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 993, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File ".../.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 286, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([128256, 4096]) in "weight" (which has shape torch.Size([32000, 4096])), this looks incorrect.

$ls run_dir
checkpoint-2400
I only see the checkpoint dir,
$ls run_dir/checkpoint-2400
adapter_config.json        latest           rng_state_1.pth  special_tokens_map.json  trainer_state.json
adapter_model.safetensors  README.md        rng_state_2.pth  tokenizer_config.json    training_args.bin
global_step2400            rng_state_0.pth  scheduler.pt     tokenizer.json           zero_to_fp32.py

How to merge Lora before training finish? It take long time and I want to check if the model is ok (by checking generation) before it is done.

Setup: Llama-3
deepspeed 2 lora finetuning

**Comment by Wintoplay** [comment]
Ok solved
I can just point at "bunny-lora-llama3-8b-Full-dataset-copy/checkpoint-2400"
model = AutoPeftModelForCausalLM.from_pretrained(
    checkpoint_path,
    device_map="auto",  # Automatically distributes the model across available GPUs/CPU
    trust_remote_code=True,
     torch_dtype=torch.float16
)
