### ISSUE TITLE
导入checkpoint

### ISSUE THREAD

**Issue by renyingxuan** [BAAI-DCAI/Bunny#141]
你好，我在预训练结束后尝试导入checkpoint的时候，会报这个错误
Traceback (most recent call last):
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1048, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 750, in __getitem__
    raise KeyError(key)
KeyError: 'bunny-phi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/Bunny-main/script/val.py", line 26, in <module>
    config = BunnyPhiConfig.from_pretrained(model_name)
  File "/root/miniconda3/envs/bunny/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1050, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `bunny-phi` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

**Comment by Isaachhh** [comment]
If you have [intsalled](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#install) Bunny, it shouldn't be like that.

The snippet in [Quickstart](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#quickstart) is used for Bunny-v1.0-3B (SigLIP + Phi-2) and so on. We manually combine some configuration code into a single file for users' convenience. Also, you can check [modeling_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/modeling_bunny_phi.py) and [configuration_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/configuration_bunny_phi.py) and their related parts in the source code of Bunny to see the difference.

For other models including models trained by yourself, we currently only support loading them with installing source code of Bunny. Or you can copy [modeling_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/modeling_bunny_phi.py) and [configuration_bunny_phi.py](https://huggingface.co/BAAI/Bunny-v1_0-3B/blob/main/configuration_bunny_phi.py) into your model and edit config.json.
